/* Sample timetable dataset transcribed from the 10 provided PDFs (13 sections).
   Each day = 9 period tokens (P1..P9, lunch = P5). "-" = free. Tokens map to subjects in `subs`.
   Replace or extend by editing this file, or load your own via CSV in the app. */
const S=s=>Object.fromEntries(s.split(';').map(x=>x.split('=')));
const G2="A=Transforms & Boundary Value Problems;B=Solid State Devices;C=Computer Organization & Architecture;D=Digital Logic Design;E=Electromagnetic Theory;F=Professional Ethics;G=Universal Human Values-II;H=Verbal Reasoning;I=Social Engineering;L=Devices & Digital IC Lab";
const MP="B=Microprocessor & Microcontroller;G=Analytical & Logical Thinking;H=Indian Art Form;L=VLSI / Microprocessor Lab;F=Community Connect";
const Y1="K=Chemistry Lab;W=Workshop;P=PPS Lab;R=Career Development (CDC);N=NSS;Q=PCB Lab";
const TIMETABLES={
"I ECE-A":{term:"Sample (2024-25 format)",subs:S("E=Philosophy of Engineering;A=Advanced Calculus;B=Chemistry;C=Electronic System & PCB;D=Programming for Problem Solving;F=Biology;G=German;"+Y1),days:{Mon:"E E B A - K K F R",Tue:"C B A D - W W W W",Wed:"B E D - - P P Q Q",Thu:"G G G A - R R N N",Fri:"D A C B - F G G G"}},
"I ECE-B / EEE":{term:"Sample (2024-25 format)",subs:S("E=Philosophy of Engineering;A=Advanced Calculus;B=Chemistry;F=Electronic System & PCB;D=Programming for Problem Solving;C=Biology;G=German;"+Y1),days:{Mon:"R F K K - E E B A",Tue:"W W W W - C B A D",Wed:"F P R R P - B E D",Thu:"N N C A - D G G G",Fri:"Q Q - G G G - B A"}},
"I ECE-DS":{term:"Sample (2024-25 format)",subs:S("E=Philosophy of Engineering;A=Advanced Calculus;B=Chemistry;C=Electronic System & PCB;D=Programming for Problem Solving;F=Biology;G=German;"+Y1),days:{Mon:"F R Q Q - E E B A",Tue:"K K N N - C B A D",Wed:"R R A - P P B E D",Thu:"F A D G G G - C B",Fri:"G G G P - W W W W"}},
"I Biotech-B / BME":{term:"Sample (2024-25 format)",subs:S("E=Philosophy of Engineering;A=Advanced Calculus;B=Chemistry;D=Programming for Problem Solving;C=Cell Biology;F=Biochemistry;J=Japanese;Y=Yoga;"+Y1),days:{Mon:"C Y Y F - E E A B",Tue:"R R C F - - B A D",Wed:"W W W W - D B E D",Thu:"K K A C - B J J J",Fri:"F R A J J J - P P"}},
"II ECE-DS A":{term:"Odd 2026-27 · Sem III",subs:S(G2),days:{Mon:"E A I I - G G L L",Tue:"C A E D - G - H H",Wed:"A B C D - - H - -",Thu:"B C A F - L L - -",Fri:"D B E C - - - - -"}},
"II ECE-DS B":{term:"Odd 2026-27 · Sem III",subs:S(G2),days:{Mon:"- - L L - D B C I",Tue:"L L - - - C D E A",Wed:"G - - - - I E A D",Thu:"G G H H - A C B E",Fri:"H - - - - F A B C"}},
"II BME":{term:"Odd 2026-27 · Sem III",subs:S("A=Transforms & Boundary Value Problems;B=Biomedical Signals & Systems;C=Electric & Electronic Circuits;D=Digital Logic for Medical Systems;E=Medical Physics;F=Professional Ethics;G=Universal Human Values-II;H=Verbal Reasoning;I=Social Engineering;L=DLMS / EEC Lab"),days:{Mon:"E C I I - L L - -",Tue:"C E B A - H H - -",Wed:"B D A - - H G - -",Thu:"A E B D - - - L L",Fri:"F A C D - - - G G"}},
"III ECE-A":{term:"Odd 2026-27 · Sem V",subs:S("A=Discrete Mathematics;C=VLSI Design & Technology;D=System & Network on Chip;E=Machine Learning for All;"+MP),days:{Mon:"E B B A - G G - -",Tue:"H D B B - - G - -",Wed:"C A D F - - - L L",Thu:"A E C F - - - - -",Fri:"D A E C - L L - -"}},
"III ECE-B":{term:"Odd 2026-27 · Sem V",subs:S("A=Discrete Mathematics;C=VLSI Design & Technology;D=System & Network on Chip;E=Machine Learning for All;"+MP),days:{Mon:"L L - - - E B A D",Tue:"G G - - - F B D C",Wed:"G - - - - B B A H",Thu:"L L - - - A C E F",Fri:"- - - - - C A E D"}},
"III ECE-DS":{term:"Odd 2026-27 · Sem V",subs:S("A=Discrete Mathematics;C=VLSI Design & Technology;D=Machine Learning for All;E=Database Design & Management;"+MP),days:{Mon:"E B C A - - - - -",Tue:"C B D F - L L - -",Wed:"H B A C - - - G G",Thu:"A D E F - - - - -",Fri:"D A E B - G - L L"}},
"III BME":{term:"Odd 2026-27 · Sem V",subs:S("A=Probability & Statistics;B=Microcontrollers in Medicine;C=Biomedical Signal Processing;D=Biometrics;E=Modern Wireless Communication;F=Principles of Medical Imaging;G=Analytical & Logical Thinking;H=Indian Art Form;I=Community Connect;M=Microcontroller Lab (MPMC);P=Bio DSP Lab"),days:{Mon:"G G M M - E B F H",Tue:"P P G - - C D A B",Wed:"- - - - - C A F D",Thu:"- - - I - A C E B",Fri:"I - - - - F A D E"}},
"IV ECE-A":{term:"Odd 2026-27 · Sem VII",subs:S("A=Behavioural Psychology;B=Wireless Comm & Antenna Systems;C=Computer Comm & Network Security;D=Semiconductor Memory Design;E=Scripting Language for EDA;F=Machine Learning for All;L=CCNS Lab"),days:{Mon:"C - A D - - - - -",Tue:"C D B F - - - - -",Wed:"B L E F - - - - -",Thu:"F A E B - - - - -",Fri:"C A D E - - - - -"}},
"IV ECE-B":{term:"Odd 2026-27 · Sem VII",subs:S("A=Behavioural Psychology;B=Wireless Comm & Antenna Systems;C=Computer Comm & Network Security;D=Semiconductor Memory Design;E=Scripting Language for EDA;F=Machine Learning for All;L=CCNS Lab"),days:{Mon:"C A E F - - - - -",Tue:"C E F B - - - - -",Wed:"C D A B - - - - -",Thu:"D B L A - - - - -",Fri:"E D F - - - - - -"}}
};
